version: '3.9'

services:

 openssl:
   image: alpine:latest
   container_name: openssl
   hostname: openssl
   build: 
     context: ./tls-init-openssl
     dockerfile: Dockerfile
   command: sh -c /tls-init/setup.sh
   volumes:
     - "${PWD}/certs:/certs"
     - "${PWD}/my-safe-directory:/my-safe-directory"
     - "${PWD}/tls-init-openssl:/tls-init"
