version: '3.9'

services:
  teleport:
    image: public.ecr.aws/gravitational/teleport-ent-distroless-debug:16.0.3
    container_name: teleport
    hostname: localhost
    ports:
      - 3023:3023
      - 3025:3025
      - 3080:3080
    volumes:
      - ./teleport/config:/etc/teleport
      - ./teleport/data:/var/lib/teleport
    depends_on:
      crdb_init:
        condition: service_healthy
