services:
  spicedb:
    container_name: spicedb_authz
    image: "authzed/spicedb:latest"
    command: "serve"
    restart: "always"
    ports:
      - "8090:8080"  # Dashboard
      - "9090:9090"  # Metrics
      - "50051:50051" # gRPC API
    environment:
      - "SPICEDB_GRPC_PRESHARED_KEY=${SPICEDB_GRPC_PRESHARED_KEY}"  # Shared key for API authentication
      - "SPICEDB_DATASTORE_ENGINE=cockroachdb"  
      - "SPICEDB_DATASTORE_CONN_URI=postgres://${POSTGRES_USER}@crdb1:26257/spicedb?sslmode=disable"
    depends_on:
      - "migrate"

  migrate:
    container_name: spicedb_migrate
    image: "authzed/spicedb:latest"
    command: "datastore migrate head"
    restart: "on-failure"
    environment:
      - "SPICEDB_DATASTORE_ENGINE=cockroachdb"  
      - "SPICEDB_DATASTORE_CONN_URI=postgres://${POSTGRES_USER}@crdb1:26257/spicedb?sslmode=disable"
    depends_on:
      - "crdb_init"
