version: '3.9'

services:
  teleport:
    user: '503'
    group_add:
    - '20'
    image: public.ecr.aws/gravitational/teleport-distroless:15.0.1
    container_name: teleport
    hostname: localhost
    ports:
      - 3023:3023
      - 3025:3025
      - 3080:3080
    volumes:
      - ./teleport/config:/etc/teleport
      - ./teleport/data:/var/lib/teleport

  crdb:
    image: cockroachdb/cockroach:latest
    container_name: cockroach
    hostname: cockroach
    ports:
      - "26257:26257"
      - "8080:8080"
    command: start-single-node --insecure
    volumes:
      - "${PWD}/cockroach-data/crdb:/cockroach/cockroach-data"
